/**
 * Configuration for JSON field extraction in Drizzle Cube
 *
 * This module defines types and defaults for extracting dimensions
 * from JSON columns (properties, traits, context) in analytics events.
 */

/**
 * Configuration for a JSON-extracted dimension
 */
export interface JsonFieldConfig {
  /** Dimension name (camelCase, used in queries) */
  name: string;
  /** Human-readable title */
  title?: string;
  /** JSONPath to extract (e.g., "$.product_id", "$.device.type") */
  path: string;
  /** Data type: "string" | "number" | "boolean" */
  type: 'string' | 'number' | 'boolean';
  /** Whether to show in UI (default: true) */
  shown?: boolean;
}

/**
 * Full cube configuration for JSON field extraction
 */
export interface CubeJsonConfig {
  /** Fields to extract from properties JSON */
  properties?: JsonFieldConfig[];
  /** Fields to extract from traits JSON */
  traits?: JsonFieldConfig[];
  /** Fields to extract from context JSON */
  context?: JsonFieldConfig[];
}

/**
 * Default JSON field configurations - aligned with event simulator data
 *
 * These fields match the data generated by EventButtons.tsx simulator
 * and common RudderStack/Segment event patterns.
 */
export const DEFAULT_CUBE_CONFIG: CubeJsonConfig = {
  properties: [
    // Track event fields (from simulator)
    { name: 'orderId', title: 'Order ID', path: '$.orderId', type: 'string' },
    { name: 'revenue', title: 'Revenue', path: '$.revenue', type: 'number' },
    { name: 'currency', title: 'Currency', path: '$.currency', type: 'string' },
    { name: 'product', title: 'Product', path: '$.product', type: 'string' },
    { name: 'quantity', title: 'Quantity', path: '$.quantity', type: 'number' },
    // Page event fields (stored in properties)
    { name: 'url', title: 'URL', path: '$.url', type: 'string' },
    { name: 'title', title: 'Title', path: '$.title', type: 'string' },
    { name: 'referrer', title: 'Referrer', path: '$.referrer', type: 'string' },
    // Batch event fields
    { name: 'batchId', title: 'Batch ID', path: '$.batchId', type: 'string' },
    { name: 'sequence', title: 'Sequence', path: '$.sequence', type: 'number' },
    // Screen event fields
    { name: 'screenName', title: 'Screen Name', path: '$.screen_name', type: 'string' },
    { name: 'appVersion', title: 'App Version', path: '$.app_version', type: 'string' },
    { name: 'platform', title: 'Platform', path: '$.platform', type: 'string' },
    { name: 'deviceType', title: 'Device Type', path: '$.device_type', type: 'string' },
  ],
  traits: [
    // Identify event fields (from simulator)
    { name: 'email', title: 'Email', path: '$.email', type: 'string' },
    { name: 'traitName', title: 'Name', path: '$.name', type: 'string' },
    { name: 'plan', title: 'Plan', path: '$.plan', type: 'string' },
    { name: 'createdAt', title: 'Created At', path: '$.createdAt', type: 'string' },
    // Group event fields (from simulator)
    { name: 'industry', title: 'Industry', path: '$.industry', type: 'string' },
    { name: 'employees', title: 'Employees', path: '$.employees', type: 'number' },
  ],
  context: [
    // Core context fields
    { name: 'ipAddress', title: 'IP Address', path: '$.ip', type: 'string' },
    { name: 'userAgent', title: 'User Agent', path: '$.userAgent', type: 'string' },
    { name: 'locale', title: 'Locale', path: '$.locale', type: 'string' },
    { name: 'timezone', title: 'Timezone', path: '$.timezone', type: 'string' },
    // Device context
    { name: 'ctxDeviceType', title: 'Device Type', path: '$.device.type', type: 'string' },
    { name: 'ctxDeviceId', title: 'Device ID', path: '$.device.id', type: 'string' },
    { name: 'deviceManufacturer', title: 'Device Manufacturer', path: '$.device.manufacturer', type: 'string' },
    { name: 'deviceModel', title: 'Device Model', path: '$.device.model', type: 'string' },
    // OS context
    { name: 'osName', title: 'OS Name', path: '$.os.name', type: 'string' },
    { name: 'osVersion', title: 'OS Version', path: '$.os.version', type: 'string' },
    // Page context
    { name: 'pageUrl', title: 'Page URL', path: '$.page.url', type: 'string' },
    { name: 'pagePath', title: 'Page Path', path: '$.page.path', type: 'string' },
    { name: 'pageTitle', title: 'Page Title', path: '$.page.title', type: 'string' },
    { name: 'pageReferrer', title: 'Page Referrer', path: '$.page.referrer', type: 'string' },
    // Campaign context (UTM parameters)
    { name: 'campaignSource', title: 'Campaign Source', path: '$.campaign.source', type: 'string' },
    { name: 'campaignMedium', title: 'Campaign Medium', path: '$.campaign.medium', type: 'string' },
    { name: 'campaignName', title: 'Campaign Name', path: '$.campaign.name', type: 'string' },
    { name: 'campaignTerm', title: 'Campaign Term', path: '$.campaign.term', type: 'string' },
    { name: 'campaignContent', title: 'Campaign Content', path: '$.campaign.content', type: 'string' },
    // Library context
    { name: 'libraryName', title: 'Library Name', path: '$.library.name', type: 'string' },
    { name: 'libraryVersion', title: 'Library Version', path: '$.library.version', type: 'string' },
    // Screen context
    { name: 'screenWidth', title: 'Screen Width', path: '$.screen.width', type: 'number' },
    { name: 'screenHeight', title: 'Screen Height', path: '$.screen.height', type: 'number' },
    { name: 'screenDensity', title: 'Screen Density', path: '$.screen.density', type: 'number' },
  ],
};

/**
 * Merge custom config with defaults
 * Custom fields are added to defaults (not replaced)
 */
export function mergeCubeConfig(
  custom: Partial<CubeJsonConfig>
): CubeJsonConfig {
  return {
    properties: [
      ...(DEFAULT_CUBE_CONFIG.properties ?? []),
      ...(custom.properties ?? []),
    ],
    traits: [
      ...(DEFAULT_CUBE_CONFIG.traits ?? []),
      ...(custom.traits ?? []),
    ],
    context: [
      ...(DEFAULT_CUBE_CONFIG.context ?? []),
      ...(custom.context ?? []),
    ],
  };
}

/**
 * Create config that replaces defaults entirely
 */
export function createCubeConfig(config: CubeJsonConfig): CubeJsonConfig {
  return config;
}
