/**
 * Event Ingest worker deployment step
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { DeployedUrls } from '../core/types.js';
import {
  getWorkersPath,
  parseJsonc,
  runCommandWithOutputAsync,
  extractWorkerUrl,
  checkWorkerDeployedAsync,
  constructWorkerUrl,
} from '../core/wrangler.js';
import { promptRedeploy } from '../core/prompts.js';

/**
 * Get worker name based on project name
 */
export function getEventIngestWorkerName(projectName: string): string {
  return `${projectName}-event-ingest`;
}

/**
 * Get paths for event-ingest worker
 */
function getPaths() {
  const workerPath = join(getWorkersPath(), 'event-ingest');
  return {
    basePath: join(workerPath, 'wrangler.jsonc'),
    localPath: join(workerPath, 'wrangler.local.jsonc'),
  };
}

/**
 * Create wrangler.local.jsonc for event-ingest worker
 */
export function createEventIngestLocalConfig(projectName: string, streamId: string): boolean {
  const { basePath, localPath } = getPaths();

  if (!existsSync(basePath)) {
    return false;
  }

  try {
    const baseContent = readFileSync(basePath, 'utf-8');
    const config = parseJsonc(baseContent) as Record<string, unknown>;

    // Set worker name based on project
    config.name = getEventIngestWorkerName(projectName);

    // Add pipeline binding
    config.pipelines = [
      {
        pipeline: streamId,
        binding: 'PIPELINE',
      },
    ];

    // Write local config with comment header
    const localContent = `// Local wrangler config - DO NOT COMMIT
// Generated by: pnpm launch
// Contains environment-specific values for your Cloudflare account
${JSON.stringify(config, null, 2)}
`;

    writeFileSync(localPath, localContent);
    return true;
  } catch {
    return false;
  }
}

/**
 * Deploy event-ingest worker (async for spinner animation)
 */
export async function deployEventIngest(): Promise<{ success: boolean; url?: string; error?: string }> {
  const { localPath } = getPaths();
  const result = await runCommandWithOutputAsync(`wrangler deploy --config "${localPath}"`);

  const output = result.output;
  const url = extractWorkerUrl(output);

  // Check for success indicators
  const successIndicators = ['Uploaded ', 'Published ', 'Current Version ID:', 'workers.dev'];
  const hasSuccessIndicator = successIndicators.some(indicator => output.includes(indicator));

  if (result.success || hasSuccessIndicator || url) {
    return { success: true, url: url || undefined };
  }
  return { success: false, error: output };
}

/**
 * Check if event-ingest worker is deployed (async for spinner animation)
 */
export async function checkEventIngestDeployedAsync(projectName: string, subdomain?: string) {
  const workerName = getEventIngestWorkerName(projectName);
  return checkWorkerDeployedAsync(workerName, subdomain);
}

/**
 * Full event-ingest setup flow
 */
export async function setupEventIngest(
  projectName: string,
  streamId: string,
  deployedUrls: DeployedUrls,
  skipPrompts = false,
  subdomain?: string
): Promise<{ success: boolean; url?: string }> {
  // Create local config
  if (!createEventIngestLocalConfig(projectName, streamId)) {
    return { success: false };
  }

  // Check if already deployed
  const status = await checkEventIngestDeployedAsync(projectName, subdomain);
  let shouldDeploy = true;

  if (status.deployed && !skipPrompts) {
    if (status.url) {
      deployedUrls.ingest = status.url;
    }
    shouldDeploy = await promptRedeploy('Event Ingest');
  }

  if (shouldDeploy) {
    const workerName = getEventIngestWorkerName(projectName);
    const result = await deployEventIngest();
    if (result.success) {
      // Use extracted URL or construct it from worker name and subdomain
      const url = result.url || constructWorkerUrl(workerName, subdomain);
      if (url) {
        deployedUrls.ingest = url;
      }
      return { success: true, url: url || undefined };
    }
    return result;
  }

  return { success: true, url: status.url || undefined };
}

/**
 * Get the config path for event-ingest worker
 */
export function getEventIngestConfigPath(): string {
  return getPaths().localPath;
}
